[providers]
providers = ["php"]

[variables]
NIXPACKS_PHP_EXTENSIONS = "pdo, pdo_mysql, mysqli, mbstring, tokenizer, xml, ctype, json, openssl, bcmath"

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"